CC=gcc

# INJECT
INJECT_INCLUDES = includes/
INJECT_SRC = src/inject.c
INJECT_CFLAGS = -g -Wall -I$(INJECT_INCLUDES) -ldl
INJECT32_DEBUG = inject32.dbg
INJECT64_DEBUG = inject64.dbg
INJECT_OBJ32 = $(INJECT_SRC:.c=32.o)
INJECT_OBJ64 = $(INJECT_SRC:.c=64.o)

.PHONY: all clean

all: $(INJECT64_DEBUG) $(INJECT32_DEBUG) 

$(INJECT32_DEBUG): $(INJECT_OBJ32)
	$(CC) $(INJECT_CFLAGS) -m32 -o $@ $(INJECT_SRC)

$(INJECT64_DEBUG): $(INJECT_OBJ64)
	$(CC) $(INJECT_CFLAGS) -m64 -o $@ $(INJECT_SRC)

$(INJECT_OBJ32): $(INJECT_SRC)
$(INJECT_OBJ64): $(INJECT_SRC)

clean:
	${RM} ${INJECT_OBJ32} ${INJECT_OBJ64} ${INJECT32_DEBUG} ${INJECT64_DEBUG} 
